
[[plugins]]
repo = 'Shougo/unite.vim'

# unite.vimを読み込んだら一緒に読み込む
[[plugins]] # 履歴プラグイン
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]] # python コード補完
repo = "davidhalter/jedi-vim"
on_source = ['python']
